apiVersion: v2
name: my-app
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: redis
    version: "20.2.1"               # Redis chart version
    repository: "https://charts.bitnami.com/bitnami"
    alias: redis-cache              # Alias for the cache instance
    condition: redis-cache.enabled  # Condition for enabling/disabling redis-cache
  - name: redis
    version: "20.2.1"               # Redis chart version
    repository: "https://charts.bitnami.com/bitnami"
    alias: redis-session            # Alias for the session instance
    condition: redis-session.enabled  # Condition for enabling/disabling redis-session